export const PARTS = [
  {
    id: "block",
    label: "Silindr bloki",
    desc: "Porshen harakatlanadigan silindr shu blok ichida. Tashqi qovurg'alar dvigatelni havo bilan sovitadi: yonishdan chiqqan issiqlikning bir qismi shular orqali tarqaladi.",
    shell: true,
    explode: [0, 0, 0],
    anchor: [1.0, 1.2, 0],
  },
  {
    id: "head",
    label: "Silindr kallagi",
    desc: "Silindrni yuqoridan berkitadi. Ichida yonish kamerasi, klapanlar va sham o'rnatiladigan teshik bor.",
    shell: true,
    explode: [0, 1.7, 0],
    anchor: [1.0, 2.3, 0.4],
  },
  {
    id: "camCover",
    label: "Klapan qopqog'i",
    desc: "Taqsimlash vallari va klapanlarni yuqoridan yopib turadi, moy sachrashini to'xtatadi.",
    shell: true,
    explode: [0, 3.0, 0],
    anchor: [0.8, 3.05, 0],
  },
  {
    id: "crankcase",
    label: "Karter",
    desc: "Tirsakli valni o'rab turadi va moyni saqlaydi. Moy ishqalanadigan qismlarni moylab, ularning yeyilishini kamaytiradi.",
    shell: true,
    explode: [0, -1.5, 0],
    anchor: [1.0, -0.5, 0.5],
  },
  {
    id: "camshafts",
    label: "Taqsimlash vallari",
    desc: "Mushtchalari klapanlarni kerakli paytda bosib ochadi. Tirsakli valdan ikki marta sekinroq aylanadi: to'rt takt davomida tirsakli val 2 marta, taqsimlash vali 1 marta aylanadi.",
    shell: false,
    explode: [0, 2.2, 0],
    anchor: [0, 3.0, 0.7],
  },
  {
    id: "valveIntake",
    label: "Kiritish klapani",
    desc: "So'rish taktida ochilib, silindrga yonilg'i va havo aralashmasini kiritadi. Qolgan taktlarda prujina uni yopiq ushlab turadi.",
    shell: false,
    explode: [-0.7, 1.2, 1.3],
    anchor: [-0.55, 2.45, 0.3],
  },
  {
    id: "valveExhaust",
    label: "Chiqarish klapani",
    desc: "Chiqarish taktida ochilib, ishlatilgan gazlarni silindrdan chiqarib yuboradi.",
    shell: false,
    explode: [0.7, 1.2, 1.3],
    anchor: [0.55, 2.45, 0.3],
  },
  {
    id: "sparkPlug",
    label: "Sham",
    desc: "Siqish takti oxirida elektr uchquni chiqaradi va siqilgan aralashmani yondiradi.",
    shell: false,
    explode: [0, 2.2, 1.4],
    anchor: [0, 3.65, 0],
  },
  {
    id: "piston",
    label: "Porshen",
    desc: "Silindr ichida yuqoriga va pastga harakatlanadi. Ish yo'li taktida kengayayotgan issiq gazlar porshenni pastga itaradi. Halqalar gaz silindrdan sizib chiqmasligini ta'minlaydi.",
    shell: false,
    explode: [0, 1.0, 0],
    anchor: [0, 1.95, 0.55],
  },
  {
    id: "pin",
    label: "Porshen barmog'i",
    desc: "Porshenni shatunga bog'laydi. Shatun shu barmoq atrofida buriladi.",
    shell: false,
    explode: [0, 1.0, 1.1],
    anchor: [0.35, 1.45, 0.3],
  },
  {
    id: "rod",
    label: "Shatun",
    desc: "Porshenning to'g'ri chiziq bo'ylab harakatini tirsakli valga uzatadi.",
    shell: false,
    explode: [0, 0.2, 1.3],
    anchor: [0.35, 0.8, 0.3],
  },
  {
    id: "crankshaft",
    label: "Tirsakli val",
    desc: "Shatundan kelgan turtkini aylanma harakatga aylantiradi. Bu aylanish uzatmalar orqali avtomobil g'ildiraklariga boradi.",
    shell: false,
    explode: [0, -0.6, 1.0],
    anchor: [0, -0.45, 0.9],
  },
  {
    id: "flywheel",
    label: "Maxovik",
    desc: "Og'ir g'ildirak. Ish yo'li taktida olgan kinetik energiyasi hisobiga qolgan uch taktda ham valni aylantirib turadi.",
    shell: false,
    explode: [0, -0.6, -1.4],
    anchor: [0.6, -0.4, -1.0],
  },
  {
    id: "timing",
    label: "Taqsimlash tasmasi",
    desc: "Tirsakli val bilan taqsimlash vallarini bog'laydi. Taqsimlash shkivlari tirsakli val shkividan ikki marta katta, shuning uchun ular ikki marta sekinroq aylanadi.",
    shell: false,
    explode: [0, 0.3, 2.2],
    anchor: [0.8, 2.3, 0.95],
  },
  {
    id: "intake",
    label: "Kiritish kollektori",
    desc: "Havo va yonilg'i aralashmasini kiritish klapaniga olib keladi.",
    shell: true,
    explode: [-1.5, 0.4, 0],
    anchor: [-2.05, 2.25, 0.2],
  },
  {
    id: "exhaust",
    label: "Chiqarish quvuri",
    desc: "Ishlatilgan gazlarni dvigateldan tashqariga olib chiqadi.",
    shell: true,
    explode: [1.6, -0.2, 0],
    anchor: [2.3, 0.6, 0],
  },
];

export const PART_BY_ID = Object.fromEntries(PARTS.map((p) => [p.id, p]));
