// Monitor and pop-up texts per reaction, condensed from docs/product-blueprint/14 (pending the teacher's review).
// table: doc 14 § 3 number, or null for the § 4 and § 5 Q9 entries. danger: past | o'rta | yuqori
export const REACTION_INFO = {
  "naoh-phenolphthalein": {
    table: 1,
    title: "Fenolftalein ishqoriy muhitda",
    equation: ["NaOH → Na⁺ + OH⁻", "fenolftalein pH > 8,2 da pushti shaklga o'tadi"],
    type: "Indikator bilan muhitni aniqlash (yangi modda hosil bo'lmaydi)",
    observation: "Rangsiz eritma darhol malina-pushti bo'ladi. Suyultirilmagan 10% NaOH da rang bir necha daqiqada asta-sekin oqaradi.",
    safety: "NaOH teri va ko'zni kuydiradi. Ko'zoynak taqing, tomizgich bilan ishlang.",
    danger: "o'rta",
  },
  "naoh-phenolphthalein-hcl": {
    table: 1,
    title: "Neytrallanish: ishqor + kislota",
    equation: ["NaOH + HCl → NaCl + H₂O", "H⁺ + OH⁻ → H₂O"],
    type: "Neytrallanish (almashinish), ekzotermik",
    observation: "Tashqi o'zgarish deyarli yo'q, eritma biroz iliydi. Fenolftalein bo'lsa ekvivalent nuqtada bitta tomchidan pushti rang yo'qoladi.",
    safety: "NaOH va HCl teri va ko'zni kuydiradi. Tomizgich bilan ishlang, ko'zoynak taqing.",
    danger: "o'rta",
  },
  "nh3-phenolphthalein": {
    table: 2,
    title: "Ammiak eritmasi — kuchsiz asos",
    equation: ["NH₃ + H₂O ⇌ NH₄⁺ + OH⁻"],
    type: "Indikator bilan muhitni aniqlash; kuchsiz asos",
    observation: "Eritma malina-pushti bo'ladi, pH ≈ 11–12 — NaOH dagidan pastroq.",
    safety: "Ammiak bug'i ko'z va nafas yo'llarini achishtiradi; hidni qo'l bilan yelpib aniqlang.",
    danger: "o'rta",
  },
  "nh3-heated": {
    table: 2,
    title: "Qizdirilganda ammiak uchib chiqadi",
    equation: ["NH₃·H₂O →(t) NH₃↑ + H₂O"],
    type: "Qaytar parchalanish (gaz uchib chiqishi)",
    observation: "O'tkir hid kuchayadi, fenolftaleinning pushti rangi asta-sekin yo'qoladi; sovitilganda rang qaytmaydi.",
    safety: "Mo'rili shkafda qizdiring; probirka og'zini hech kimga qaratmang.",
    danger: "o'rta",
  },
  "nahco3-water": {
    table: 3,
    title: "Natriy gidrokarbonatning erishi",
    equation: ["NaHCO₃(q) → Na⁺(e) + HCO₃⁻(e)", "HCO₃⁻ + H₂O ⇌ H₂CO₃ + OH⁻"],
    type: "Fizik jarayon (erish) va gidroliz",
    observation: "Kukun aralashtirilganda eriydi, eritma tiniq qoladi; indikator qog'ozi kuchsiz ishqoriy muhitni (pH ≈ 8,3) ko'rsatadi.",
    safety: "Past xavf; kukunni ko'zga tegizmang.",
    danger: "past",
  },
  "agno3-hcl": {
    table: 4,
    title: "Kumush xlorid cho'kmasi",
    equation: ["AgNO₃ + HCl → AgCl↓ + HNO₃", "Ag⁺ + Cl⁻ → AgCl↓"],
    type: "Ion almashinish (cho'kma); xlorid ioniga sifat reaksiyasi",
    observation: "Darhol oq, suzmasimon cho'kma hosil bo'ladi va asta-sekin idish tubiga yig'iladi.",
    safety: "AgNO₃ terida qora dog' qoldiradi. Kumush chiqindilarini alohida idishga yig'ing.",
    danger: "past",
  },
  "agno3-ki": {
    table: 5,
    title: "Kumush yodid cho'kmasi",
    equation: ["AgNO₃ + KI → AgI↓ + KNO₃", "Ag⁺ + I⁻ → AgI↓"],
    type: "Ion almashinish (cho'kma); yodid ioniga sifat reaksiyasi",
    observation: "Och sariq (somonrang) mayda cho'kma tushadi. AgCl dan farqi — sariq rang va ammiakda erimasligi.",
    safety: "AgNO₃ dog' qoldiradi; ko'zoynak taqing.",
    danger: "past",
  },
  "cuso4-naoh": {
    table: 6,
    title: "Mis(II) gidroksid cho'kmasi",
    equation: ["CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄", "Cu²⁺ + 2OH⁻ → Cu(OH)₂↓"],
    type: "Ion almashinish (cho'kma); Cu²⁺ ioniga sifat reaksiyasi",
    observation: "Ko'k eritmada darhol havorang, iviqsimon cho'kma paydo bo'ladi; ishqor yetarli bo'lsa ustidagi eritma rangsizlanadi.",
    safety: "NaOH ishqor — ko'zoynak va ehtiyotkorlik.",
    danger: "o'rta",
  },
  "cuso4-naoh-heat": {
    table: 6,
    title: "Cu(OH)₂ ning parchalanishi",
    equation: ["Cu(OH)₂ →(t) CuO + H₂O"],
    type: "Parchalanish (qizdirilganda), endotermik",
    observation: "Havorang cho'kma qizdirilganda qorayib, qora kukunsimon CuO ga aylanadi, bug' chiqadi.",
    safety: "Qizdirilgan suspenziya otilib chiqishi mumkin: probirkani qiya ushlab, tebratib qizdiring.",
    danger: "o'rta",
  },
  "hydroxide-acid": {
    table: 6,
    title: "Cho'kma kislotada eriydi",
    equation: ["Cu(OH)₂ + 2HCl → CuCl₂ + 2H₂O", "Fe(OH)₃ + 3HCl → FeCl₃ + 3H₂O"],
    type: "Neytrallanish (asos yoki asosli oksid + kislota)",
    observation: "Cho'kma erib ketadi va metall ionining rangi eritmaga qaytadi: mis bilan ko'k, temir bilan sariq-qo'ng'ir.",
    safety: "Kislota sachrashidan ko'zni himoya qiling.",
    danger: "o'rta",
  },
  "fecl3-naoh": {
    table: 7,
    title: "Temir(III) gidroksid cho'kmasi",
    equation: ["FeCl₃ + 3NaOH → Fe(OH)₃↓ + 3NaCl", "FeCl₃ + 3NH₃·H₂O → Fe(OH)₃↓ + 3NH₄Cl"],
    type: "Ion almashinish (cho'kma); Fe³⁺ ioniga sifat reaksiyasi",
    observation: "Qizg'ish-qo'ng'ir (zang rang) iviqsimon cho'kma tushadi; ortiqcha ishqorda ham, ammiakda ham erimaydi.",
    safety: "FeCl₃ va ishqorlar yemiruvchi; ammiak hidini yelpib aniqlang.",
    danger: "o'rta",
  },
  "limewater-co2": {
    table: 8,
    title: "Ohak suvining loyqalanishi",
    equation: ["Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O"],
    type: "Kislotali oksid + asos; CO₂ ga sifat reaksiyasi",
    observation: "Tiniq eritma bir necha soniyada sutdek oq loyqa bo'ladi — mayda CaCO₃ zarrachalari muallaq turadi.",
    safety: "Ohak suvi ko'zni achishtiradi; ko'zoynak taqing.",
    danger: "past",
  },
  "limewater-co2-excess": {
    table: 8,
    title: "Ortiqcha CO₂ loyqani yo'qotadi",
    equation: ["CaCO₃ + CO₂ + H₂O → Ca(HCO₃)₂"],
    type: "Birikish (eruvchan gidrokarbonat hosil bo'lishi)",
    observation: "Gaz o'tkazish davom etsa oq loyqa asta-sekin yo'qoladi va eritma yana tiniqlashadi.",
    safety: "Past xavf.",
    danger: "past",
  },
  "limewater-co2-heat": {
    table: 8,
    title: "Ca(HCO₃)₂ qizdirilganda",
    equation: ["Ca(HCO₃)₂ →(t) CaCO₃↓ + CO₂↑ + H₂O"],
    type: "Parchalanish (qizdirilganda)",
    observation: "Tiniq eritma qizdirilganda yana oq loyqa bo'ladi va mayda pufakchalar chiqadi.",
    safety: "Issiq idishni qo'l bilan ushlamang.",
    danger: "past",
  },
  "co2-naoh": {
    table: null,
    title: "CO₂ ishqorga yutiladi (ko'rinmaydi)",
    equation: ["2NaOH + CO₂ → Na₂CO₃ + H₂O"],
    type: "Kislotali oksid + asos",
    observation: "Reaksiya boradi, lekin Na₂CO₃ suvda eriydi — ohak suvidan farqli ravishda loyqa hosil bo'lmaydi.",
    safety: "NaOH yemiruvchi.",
    danger: "o'rta",
  },
  "cuso4-nh3": {
    table: 9,
    title: "Oz ammiak: havorang cho'kma",
    equation: ["2CuSO₄ + 2NH₃·H₂O → (CuOH)₂SO₄↓ + (NH₄)₂SO₄"],
    type: "Ion almashinish (asosli tuz cho'kmasi)",
    observation: "Birinchi tomchilarda och ko'k-yashilroq (havorang) mayda cho'kma paydo bo'ladi.",
    safety: "Ammiak bug'i achishtiradi; mis tuzlari chiqindisi alohida idishga.",
    danger: "o'rta",
  },
  "cuso4-nh3-excess": {
    table: 9,
    title: "Ortiqcha ammiak: to'q ko'k kompleks",
    equation: ["Cu(OH)₂ + 4NH₃ → [Cu(NH₃)₄](OH)₂", "CuSO₄ + 4NH₃ → [Cu(NH₃)₄]SO₄"],
    type: "Kompleks birikma hosil bo'lishi; Cu²⁺ ioniga sifat reaksiyasi",
    observation: "Cho'kma erib ketadi, eritma tiniq va siyohrang-ko'k bo'ladi — boshlang'ich CuSO₄ dan ancha to'q.",
    safety: "Ammiak bug'i; mis chiqindisi alohida idishga.",
    danger: "o'rta",
  },
  "nahco3-hcl": {
    table: 10,
    title: "Karbonat + kislota → CO₂",
    equation: ["NaHCO₃ + HCl → NaCl + H₂O + CO₂↑", "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑"],
    type: "Ion almashinish (gaz ajralishi); karbonatlarga sifat reaksiyasi",
    observation: "Soda bilan shiddatli ko'piklanish va vishillash, idish soviydi; marmar bilan pufakchalar bir tekis chiqadi va bo'lak asta-sekin kichrayadi.",
    safety: "Kukunni oz-ozdan qo'shing — ko'pik toshib ketmasin; ko'zoynak taqing.",
    danger: "past",
  },
  "metal-hcl-hydrogen": {
    table: 11,
    title: "Metall + xlorid kislota → vodorod",
    equation: ["Mg + 2HCl → MgCl₂ + H₂↑", "Zn + 2HCl → ZnCl₂ + H₂↑", "Fe + 2HCl → FeCl₂ + H₂↑"],
    type: "O'rin olish, oksidlanish-qaytarilish",
    observation: "Metall sirtidan vodorod pufakchalari chiqadi: magniyda juda tez va issiq, ruxda o'rtacha, temirda sekin — eritma och yashil tus oladi.",
    safety: "Vodorod yonuvchan: alanga yaqinida ishlamang, probirkani tiqin bilan yopmang.",
    danger: "o'rta",
  },
  "metal-h2so4-hydrogen": {
    table: 12,
    title: "Metall + suyultirilgan sulfat kislota",
    equation: ["Zn + H₂SO₄ → ZnSO₄ + H₂↑", "Mg + H₂SO₄ → MgSO₄ + H₂↑", "Fe + H₂SO₄ → FeSO₄ + H₂↑"],
    type: "O'rin olish, oksidlanish-qaytarilish",
    observation: "№ 11 dagidek vodorod ajraladi. Muhim: vodorodni faqat suyultirilgan kislota beradi.",
    safety: "Suyultirishda \"kislotani suvga\" qoidasiga rioya qiling; H₂ yonuvchan.",
    danger: "o'rta",
  },
  "zn-h2so4-conc": {
    table: 13,
    title: "Rux + kons. sulfat kislota → SO₂",
    equation: ["Zn + 2H₂SO₄(kons.) →(t) ZnSO₄ + SO₂↑ + 2H₂O", "3Zn + 4H₂SO₄ → 3ZnSO₄ + S↓ + 4H₂O"],
    type: "Oksidlanish-qaytarilish (oksidlovchi — S⁺⁶, vodorod ioni emas)",
    observation: "Sovuqda kam pufakchalar; qizdirilganda o'tkir, bo'g'uvchi SO₂ hidi va sarg'ish loyqa (oltingugurt). Vodorod ajralmaydi.",
    safety: "Yuqori xavf: kons. H₂SO₄ kuydiradi, SO₂ va H₂S zaharli. Faqat mo'rili shkafda, qo'lqop va ko'zoynakda.",
    danger: "yuqori",
  },
  "cu-h2so4-conc": {
    table: 14,
    title: "Mis va temir + kons. sulfat kislota",
    equation: ["Cu + 2H₂SO₄(kons.) →(t) CuSO₄ + SO₂↑ + 2H₂O", "2Fe + 6H₂SO₄(kons.) →(t) Fe₂(SO₄)₃ + 3SO₂↑ + 6H₂O"],
    type: "Oksidlanish-qaytarilish (faqat qizdirilganda)",
    observation: "Sovuqda o'zgarish yo'q. Qizdirilganda pufakchalar va bo'g'uvchi SO₂; mis bilan suyuqlik qorayadi va tubida oq-kulrang cho'kma qoladi.",
    safety: "Yuqori xavf: qaynoq kons. kislota, SO₂ zaharli. Issiq aralashmaga suv quyilmaydi.",
    danger: "yuqori",
  },
  "h2o2-mno2": {
    table: 15,
    title: "H₂O₂ ning katalitik parchalanishi",
    equation: ["2H₂O₂ →(MnO₂) 2H₂O + O₂↑"],
    type: "Katalitik parchalanish, oksidlanish-qaytarilish; ekzotermik",
    observation: "Qora kukun tushishi bilan shiddatli ko'piklanish boshlanadi, idish iliydi; MnO₂ o'zgarmay qoladi va filtrlab ajratiladi.",
    safety: "Idish og'zini yopmang. 30% H₂O₂ qaynab sachraydi va teriga tegsa kuydiradi.",
    danger: "o'rta",
  },
  "h2o2-ki": {
    table: 16,
    title: "H₂O₂ + KI: kislorod va yod",
    equation: ["2H₂O₂ →(I⁻) 2H₂O + O₂↑", "H₂O₂ + 2KI → I₂ + 2KOH"],
    type: "Katalitik parchalanish; oksidlanish-qaytarilish",
    observation: "Eritma sariq, so'ng sarg'ish-qo'ng'ir bo'ladi; mayda pufakchalar bir tekis chiqadi (MnO₂ dagidan sekinroq), idish biroz iliydi.",
    safety: "30% H₂O₂ ni avval suyultiring; yod teri va kiyimda dog' qoldiradi.",
    danger: "o'rta",
  },
  "cu-hno3": {
    table: 17,
    title: "Mis + nitrat kislota",
    equation: ["Cu + 4HNO₃(kons.) → Cu(NO₃)₂ + 2NO₂↑ + 2H₂O", "3Cu + 8HNO₃(suyul.) → 3Cu(NO₃)₂ + 2NO↑ + 4H₂O"],
    type: "Oksidlanish-qaytarilish (oksidlovchi — nitrat ioni)",
    observation: "Konsentrlangan kislota bilan qo'ng'ir NO₂ toshib chiqadi va eritma yashil bo'ladi; suyultirilgani bilan rangsiz NO ajraladi va havoda qo'ng'irlashadi, eritma ko'k. Boshqa metallar ham nitrat kislota bilan vodorod bermaydi — azot oksidlari ajraladi.",
    safety: "Yuqori xavf: NO₂ juda zaharli, ta'siri kechikib kuchayadi. Faqat mo'rili shkafda, qo'lqop va ko'zoynakda.",
    danger: "yuqori",
  },
  "kmno4-heat": {
    table: 18,
    title: "KMnO₄ ning qizdirilganda parchalanishi",
    equation: ["2KMnO₄ →(t) K₂MnO₄ + MnO₂ + O₂↑"],
    type: "Parchalanish (qizdirilganda), oksidlanish-qaytarilish",
    observation: "To'q binafsha kristallar chirsillab sakraydi, modda qoramtir kukunga aylanadi; ajralgan gaz cho'g'langan cho'pni alangalantiradi.",
    safety: "Issiq shisha; KMnO₄ changi terini bo'yaydi. Spirt, glitserin va qog'oz yaqinida qizdirmang.",
    danger: "o'rta",
  },
  "metal-displacement": {
    table: 19,
    title: "Faolroq metall kamroq faolini siqib chiqaradi",
    equation: ["Fe + CuSO₄ → FeSO₄ + Cu↓", "Zn + CuSO₄ → ZnSO₄ + Cu↓", "Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag↓"],
    type: "O'rin olish, oksidlanish-qaytarilish (faollik qatori)",
    observation: "Metall sirti bir necha soniyada qoplanadi: temirda qizg'ish mis, ruxda qora-jigarrang g'ovak qatlam, mis simda kumushrang kristallar. Eritmaning rangi asta-sekin o'zgaradi.",
    safety: "Mis va kumush chiqindilarini alohida idishga yig'ing.",
    danger: "past",
  },
  "ki-fecl3": {
    table: 22,
    title: "KI + FeCl₃ → yod",
    equation: ["2FeCl₃ + 2KI → 2FeCl₂ + I₂ + 2KCl", "2Fe³⁺ + 2I⁻ → 2Fe²⁺ + I₂"],
    type: "Oksidlanish-qaytarilish (Fe³⁺ — oksidlovchi, I⁻ — qaytaruvchi)",
    observation: "Eritma to'q qo'ng'ir bo'ladi — ikkala boshlang'ich eritmadan ham to'qroq; cho'kma yo'q.",
    safety: "FeCl₃ yemiruvchi; yod dog' qoldiradi.",
    danger: "past",
  },
  "cl2-ki": {
    table: 23,
    title: "Xlor yodni siqib chiqaradi",
    equation: ["Cl₂ + 2KI → 2KCl + I₂", "Cl₂ + 2I⁻ → 2Cl⁻ + I₂"],
    type: "O'rin olish (faolroq galogen), oksidlanish-qaytarilish",
    observation: "Rangsiz eritma avval sariq, so'ng qo'ng'ir bo'ladi; o'tkir, bo'g'uvchi hid seziladi.",
    safety: "Yuqori xavf: Cl₂ zaharli. Faqat mo'rili shkafda; ortiqcha xlorni NaOH eritmasiga yuttiring.",
    danger: "yuqori",
  },
  "cl2-ki-excess": {
    table: 23,
    title: "Ortiqcha xlor yodni rangsizlantiradi",
    equation: ["I₂ + 5Cl₂ + 6H₂O → 2HIO₃ + 10HCl"],
    type: "Oksidlanish-qaytarilish (yodning yodat kislotagacha oksidlanishi)",
    observation: "Xlor uzoq o'tkazilsa qo'ng'ir rang yana yo'qoladi va eritma rangsizlanadi.",
    safety: "Xlor zaharli — mo'rili shkaf shart.",
    danger: "yuqori",
  },
  "kmno4-h2o2-acid": {
    table: 24,
    title: "KMnO₄ + H₂O₂ kislotali muhitda",
    equation: ["2KMnO₄ + 5H₂O₂ + 3H₂SO₄ → 2MnSO₄ + K₂SO₄ + 5O₂↑ + 8H₂O", "2MnO₄⁻ + 5H₂O₂ + 6H⁺ → 2Mn²⁺ + 5O₂↑ + 8H₂O"],
    type: "Oksidlanish-qaytarilish (H₂O₂ — qaytaruvchi)",
    observation: "Har tomchida pufakchalar chiqadi va binafsha rang yo'qoladi; yetarli H₂O₂ da eritma to'liq rangsiz va tiniq bo'ladi.",
    safety: "KMnO₄ kuchli oksidlovchi, kiyimni bo'yaydi; kislota bilan ehtiyot bo'ling.",
    danger: "o'rta",
  },
  "kmno4-h2o2-neutral": {
    table: 24,
    title: "KMnO₄ + H₂O₂ kislotasiz muhitda",
    equation: ["2KMnO₄ + 3H₂O₂ → 2MnO₂↓ + 2KOH + 3O₂↑ + 2H₂O"],
    type: "Oksidlanish-qaytarilish; mahsulot muhitga bog'liq",
    observation: "Binafsha eritma qo'ng'ir-loyqa bo'ladi va qo'ng'ir-qora MnO₂ cho'kmasi tushadi; hosil bo'lgan MnO₂ qolgan H₂O₂ ni parchalashda davom etadi.",
    safety: "KMnO₄ teri va kiyimni bo'yaydi.",
    danger: "o'rta",
  },
  "cuso4-ki": {
    table: 25,
    title: "CuSO₄ + KI → CuI va yod",
    equation: ["2CuSO₄ + 4KI → 2CuI↓ + I₂ + 2K₂SO₄", "2Cu²⁺ + 4I⁻ → 2CuI↓ + I₂"],
    type: "Oksidlanish-qaytarilish (Cu²⁺ → Cu⁺) va cho'kma hosil bo'lishi",
    observation: "Ko'k eritma darhol qo'ng'ir va loyqa bo'ladi; tindirilganda tubida och sarg'ish-jigarrang cho'kma qoladi.",
    safety: "Yod dog' qoldiradi; mis chiqindisi alohida idishga.",
    danger: "past",
  },
  "glycerol-cuoh2": {
    table: 26,
    title: "Glitserin + Cu(OH)₂ → to'q ko'k eritma",
    equation: ["2C₃H₅(OH)₃ + Cu(OH)₂ → [C₃H₅(OH)₂O]₂Cu + 2H₂O"],
    type: "Ko'p atomli spirtlarga sifat reaksiyasi (kompleks hosil bo'lishi)",
    observation: "Havorang cho'kma chayqatilganda erib ketadi, eritma tiniq va yorqin to'q ko'k bo'ladi. Shakar bilan ham shunday; etanol bilan erimaydi.",
    safety: "NaOH ishqor; ko'zoynak taqing.",
    danger: "o'rta",
  },
  "mg-burning": {
    table: 27,
    title: "Magniyning yonishi",
    equation: ["2Mg + O₂ → 2MgO", "2Mg + CO₂ → 2MgO + C"],
    type: "Birikish (yonish), oksidlanish-qaytarilish; kuchli ekzotermik",
    observation: "Lenta ko'zni qamashtiruvchi oq alanga bilan yonadi, oq tutun chiqadi va oq kukun (MgO) qoladi. CO₂ ichida ham yonishda davom etadi va qora qurum beradi.",
    safety: "Alangaga tik qaramang. Yonayotgan magniyni suv ham, CO₂ ham o'chirmaydi — quruq qum ishlatiladi.",
    danger: "o'rta",
  },
  "mgo-water": {
    table: 27,
    title: "MgO suv bilan — asosli oksid",
    equation: ["MgO + H₂O → Mg(OH)₂"],
    type: "Birikish; asosli oksidning xossasi",
    observation: "Oq kukun suvda kam eriydi, eritma kuchsiz ishqoriy bo'ladi va fenolftalein och pushti tus beradi.",
    safety: "Past xavf.",
    danger: "past",
  },
  "ethanol-burning": {
    table: 29,
    title: "Etanolning yonishi",
    equation: ["C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O"],
    type: "Yonish (to'liq oksidlanish), ekzotermik",
    observation: "Och ko'k, yorug' xonada deyarli ko'rinmaydigan alanga; tutun va qurum yo'q, kosacha qiziydi. 1 ml taxminan 25–60 s yonib, o'zi o'chadi.",
    safety: "Alanga ko'rinmasligi xavfli. Yonib turgan kosachaga spirt quymang; o'chirish uchun plastinka bilan yoping.",
    danger: "o'rta",
  },
  "sulfur-burning": {
    table: 30,
    title: "Oltingugurtning yonishi",
    equation: ["S + O₂ → SO₂", "SO₂ + H₂O ⇌ H₂SO₃"],
    type: "Birikish (yonish), oksidlanish-qaytarilish; ekzotermik",
    observation: "Sariq kukun avval eriydi va qizg'ish-qo'ng'ir bo'ladi, so'ng xira ko'k alanga bilan yonadi. Kislorodda alanga kattalashib yorqin ko'k-binafsha rangga kiradi.",
    safety: "Yuqori xavf: SO₂ zaharli, nafas yo'llarini kuydiradi. Faqat mo'rili shkafda va oz miqdorda.",
    danger: "yuqori",
  },
  "h2-test": {
    table: 32,
    title: "Vodorodning tozaligini tekshirish",
    equation: ["2H₂ + O₂ → 2H₂O"],
    type: "Birikish (yonish), oksidlanish-qaytarilish",
    observation: "Toza vodorod bo'g'iq \"pax\" ovozi bilan yonadi; havo aralashgan bo'lsa baland, chiyillagan ovoz eshitiladi. Probirka devorlari terlaydi.",
    safety: "Sinov faqat probirka hajmida bajariladi; katta idish yoki ballon og'zida sinalmaydi.",
    danger: "o'rta",
  },
  "h2-o2-explosion": {
    table: 33,
    title: "Qaldiroq gazning portlashi",
    equation: ["2H₂ + O₂ → 2H₂O"],
    type: "Birikish; portlash (juda tez ekzotermik reaksiya)",
    observation: "Alanga tegishi bilan qattiq portlash va yorqin chaqnash; shisha silindr sinadi, qopqoq otilib ketadi, oq bug' tumani qoladi.",
    safety: "Yuqori xavf: o'quvchilar hech qachon takrorlamaydi. Vodorod bilan ishlashdan oldin uning tozaligi tekshiriladi.",
    danger: "yuqori",
  },
  "kmno4-glycerin": {
    table: 34,
    title: "KMnO₄ + glitserin — o'z-o'zidan alangalanish",
    equation: ["14KMnO₄ + 4C₃H₅(OH)₃ → 7K₂CO₃ + 7Mn₂O₃ + 5CO₂↑ + 16H₂O"],
    type: "Oksidlanish-qaytarilish; o'z-o'zidan alangalanish, kuchli ekzotermik",
    observation: "10–30 s hech narsa bo'lmaydi, so'ng oq bug'-tutun chiqadi, vishillaydi va birdan binafsha tusli yorqin alanga bilan yonadi; qoramtir kul qoladi.",
    safety: "Yuqori xavf: kechikkan alanga. Tomizgandan keyin kosacha ustiga engashmang, yonuvchan moddalardan uzoqda bajaring.",
    danger: "yuqori",
  },
  "na-cl2": {
    table: 35,
    title: "Natriy + xlor → osh tuzi",
    equation: ["2Na + Cl₂ → 2NaCl"],
    type: "Birikish, oksidlanish-qaytarilish; yonish",
    observation: "Erigan natriy xlorda yorqin sariq alanga bilan yonadi; silindr oq tutunga to'ladi, xlorning sarg'ish-yashil rangi so'nadi, devorlarda oq kukun qoladi.",
    safety: "Yuqori xavf: Cl₂ zaharli, natriy kuydiradi. Faqat mo'rili shkafda va o'qituvchi namoyishida.",
    danger: "yuqori",
  },
  "fe-s": {
    table: 36,
    title: "Temir + oltingugurt → FeS",
    equation: ["Fe + S →(t) FeS"],
    type: "Birikish; ekzotermik",
    observation: "30–90 s qizdirilgach bir joyda qizil cho'g' paydo bo'ladi va lampa olib qo'yilgandan keyin ham butun aralashma bo'ylab o'zi tarqaladi; sovigach qora-kulrang qattiq massa qoladi.",
    safety: "Oz SO₂ ajraladi — mo'rili shkafda ishlang; issiq probirka yorilishi mumkin.",
    danger: "o'rta",
  },
  "na-water": {
    table: 37,
    title: "Natriy + suv",
    equation: ["2Na + 2H₂O → 2NaOH + H₂↑"],
    type: "O'rin olish, oksidlanish-qaytarilish; ekzotermik",
    observation: "Natriy suv yuzasida erib kumushrang sharchaga aylanadi, vishillab yuguradi va 10–20 s da yo'qoladi; oxirida kichik \"chirs\" etgan portlash bo'ladi. Katta bo'lakda vodorod sariq alanga bilan yonadi.",
    safety: "Yuqori xavf: faqat keng idishda (kristallizator), kichik bo'lak bilan, 1 m masofadan, ko'zoynakda. Natriyni qo'l bilan ushlamang.",
    danger: "yuqori",
  },
  "sodium-water-phenolphthalein": {
    table: 38,
    title: "Hosil bo'lgan ishqorni aniqlash",
    equation: ["2Na + 2H₂O → 2NaOH + H₂↑", "NaOH → Na⁺ + OH⁻"],
    type: "Indikator bilan hosil bo'lgan ishqorni aniqlash",
    observation: "Yugurayotgan natriy ortidan malina-pushti izlar paydo bo'ladi va suv bo'ylab tarqaladi; oxirida butun suv bir tekis pushti bo'ladi.",
    safety: "Hosil bo'lgan eritma — ishqor; teriga tegizmang.",
    danger: "yuqori",
  },
  "sugar-h2so4": {
    table: 39,
    title: "Shakar + kons. sulfat kislota → ko'mir ustuni",
    equation: ["C₁₂H₂₂O₁₁ →(H₂SO₄) 12C + 11H₂O", "C + 2H₂SO₄ → CO₂↑ + 2SO₂↑ + 2H₂O"],
    type: "Degidratlanish (suvni tortib olish) + oksidlanish-qaytarilish; kuchli ekzotermik",
    observation: "Oq shakar sarg'ayadi → jigarrang → qora bo'ladi, aralashma qiziydi va vishillaydi; so'ng qora, g'ovak ko'mir ustuni stakan og'zidan yuqoriga ko'tariladi.",
    safety: "Yuqori xavf: kons. H₂SO₄ kuydiradi, SO₂ zaharli. Faqat mo'rili shkafda; ustunga qo'l tegizmang.",
    danger: "yuqori",
  },
  "water-into-acid": {
    table: 40,
    title: "Suvni kislotaga quyish — XATO usul",
    equation: ["H₂SO₄ + H₂O → H₃O⁺ + HSO₄⁻ + Q"],
    type: "Gidratlanish (fizik-kimyoviy jarayon), kuchli ekzotermik",
    observation: "Suv kislota ustida qoladi va chegarada bir zumda qaynaydi: vishillash, chirsillash, kislota tomchilari idishdan otilib sachraydi; yupqa shisha yorilishi mumkin.",
    safety: "Yuqori xavf: sachragan kislota yuz va ko'zni kuydiradi. Qoida: \"Kislotani suvga quy — suvni kislotaga emas!\"",
    danger: "yuqori",
  },
  "acid-into-water": {
    table: 41,
    title: "Kislotani suvga quyish — TO'G'RI usul",
    equation: ["H₂SO₄ + nH₂O → H₂SO₄·nH₂O + Q"],
    type: "Suyultirish (gidratlanish), ekzotermik",
    observation: "Og'ir kislota tubiga cho'kadi, suyuqlikda to'lqinsimon shaffof chiziqlar (shliren) ko'rinadi; eritma sachramasdan sezilarli qiziydi va aralashtirilgach bir jinsli bo'ladi.",
    safety: "Kislotani idish devori bo'ylab sekin quying va darhol aralashtiring; idish issiq bo'ladi.",
    danger: "o'rta",
  },
  "kmno4-water": {
    table: 42,
    title: "KMnO₄ kristalining erishi va diffuziyasi",
    equation: ["KMnO₄(q) → K⁺(e) + MnO₄⁻(e)"],
    type: "Fizik jarayon (erish, diffuziya)",
    observation: "Kristall tubiga cho'kadi va atrofidan binafsha \"tutunsimon\" oqimlar tarqaladi; aralashtirilganda bir necha soniyada butun suv bir tekis pushti-binafsha bo'ladi. Harorat o'zgarmaydi.",
    safety: "Kristallarni qo'l bilan ushlamang — teri qo'ng'ir bo'yaladi; kuchli oksidlovchi.",
    danger: "past",
  },
  "sugar-water": {
    table: 43,
    title: "Shakarning erishi",
    equation: ["C₁₂H₂₂O₁₁(q) → C₁₂H₂₂O₁₁(e)"],
    type: "Fizik jarayon (erish; molekulalar ionlarga ajralmaydi)",
    observation: "Kristallar aralashtirilganda 5–30 s da to'liq eriydi, eritma tiniq va rangsiz qoladi; issiq suvda tezroq eriydi. Filtrdan to'liq o'tib ketadi.",
    safety: "Past xavf.",
    danger: "past",
  },
  "solids-water": {
    table: 43,
    title: "Erimaydigan moddalar suvda",
    equation: ["kimyoviy tenglama yo'q"],
    type: "Fizik jarayon (erimaslik, filtrlash)",
    observation: "Oltingugurt ho'llanmaydi va suv yuzasida suzib qoladi; MnO₂ qora loyqa berib asta-sekin cho'kadi; temir qipig'i darhol tubiga tushadi. Filtrlashda ular filtr qog'ozida qoladi.",
    safety: "Past xavf.",
    danger: "past",
  },
  "cuso4-dilution": {
    table: 44,
    title: "Rangli eritmani suyultirish",
    equation: ["C₁·V₁ = C₂·V₂"],
    type: "Fizik jarayon (suyultirish; ionlar soni o'zgarmaydi)",
    observation: "Ko'k eritma aralashtirilgach bir tekis och ko'k bo'ladi, keyingi suyultirishda deyarli rangsiz ko'kish qoladi. Cho'kma, gaz va issiqlik yo'q.",
    safety: "Mis tuzlari chiqindisi alohida idishga.",
    danger: "past",
  },
  "ethanol-water": {
    table: 45,
    title: "Etanol va suvning aralashishi",
    equation: ["kimyoviy tenglama yo'q (vodorod bog'lar hosil bo'ladi)"],
    type: "Fizik jarayon (cheksiz aralashish, hajm kamayishi)",
    observation: "Suyuqliklar to'liq aralashadi, umumiy hajm 100 ml emas, ≈ 96–97 ml bo'ladi; aralashma biroz iliydi va mayda pufakchalar chiqishi mumkin.",
    safety: "Etanol yonuvchan — alangadan uzoqda ishlang.",
    danger: "past",
  },
  "cu-acid-none": {
    table: null,
    title: "Mis kislotada erimaydi",
    equation: ["Cu + HCl → reaksiya bormaydi", "Cu + H₂SO₄(suyul.) → reaksiya bormaydi"],
    type: "Reaksiya bo'lmaydi (faollik qatori)",
    observation: "O'zgarish yo'q: mis faollik qatorida vodoroddan keyin turadi va kislotadan vodorodni siqib chiqara olmaydi. Kons. H₂SO₄ bilan faqat qizdirilganda reaksiya boradi.",
    safety: "Kislotalar yemiruvchi.",
    danger: "past",
  },
  "fe-passivation": {
    table: null,
    title: "Temirning passivlanishi",
    equation: ["Fe + kons. H₂SO₄ (sovuqda) → himoya oksid parda"],
    type: "Reaksiya bo'lmaydi (passivlanish)",
    observation: "Sovuq konsentrlangan kislotada temir sirtida yupqa himoya oksid parda hosil bo'ladi va reaksiya to'xtaydi. Shuning uchun kons. H₂SO₄ po'lat sisternalarda tashiladi.",
    safety: "Konsentrlangan kislotalar kuchli kuydiradi.",
    danger: "yuqori",
  },
  "na-ethanol": {
    table: null,
    title: "Natriy + etanol",
    equation: ["2Na + 2C₂H₅OH → 2C₂H₅ONa + H₂↑"],
    type: "O'rin olish, oksidlanish-qaytarilish",
    observation: "Reaksiya suvdagidan ancha sekin: natriy spirtda cho'kadi, sharchaga aylanmaydi va yonmaydi, sirtidan bir tekis pufakchalar chiqadi.",
    safety: "Ajralgan vodorod va spirt bug'i yonuvchan — alangadan uzoqda bajaring.",
    danger: "yuqori",
  },
  "mg-hot-water": {
    table: null,
    title: "Magniy + qaynoq suv",
    equation: ["Mg + 2H₂O →(t) Mg(OH)₂ + H₂↑"],
    type: "O'rin olish, oksidlanish-qaytarilish",
    observation: "Sovuq suvda deyarli sezilmaydi (sirtida oksid parda); qaynoq suvda sekin vodorod ajraladi va fenolftalein och pushti bo'ladi.",
    safety: "Qaynoq suv va issiq probirka bilan ehtiyot bo'ling.",
    danger: "past",
  },
  "zn-naoh-hydrogen": {
    table: null,
    title: "Rux + ishqor (amfoterlik)",
    equation: ["Zn + 2NaOH + 2H₂O → Na₂[Zn(OH)₄] + H₂↑"],
    type: "O'rin olish, oksidlanish-qaytarilish; ruxning amfoterligi",
    observation: "Xona haroratida juda sekin; qizdirilganda granula sirtidan sezilarli vodorod pufakchalari chiqadi.",
    safety: "Ishqor yemiruvchi; vodorod yonuvchan.",
    danger: "o'rta",
  },
  "zn-naoh-amphoteric": {
    table: null,
    title: "Zn(OH)₂ ortiqcha ishqorda eriydi",
    equation: ["Zn²⁺ + 2OH⁻ → Zn(OH)₂↓", "Zn(OH)₂ + 2NaOH → Na₂[Zn(OH)₄]"],
    type: "Cho'kma hosil bo'lishi va amfoter gidroksidning erishi",
    observation: "Avval oq cho'kma tushadi, ishqor ortiqcha qo'shilganda u erib ketadi va eritma yana tiniq bo'ladi.",
    safety: "Ishqor teri va ko'zni kuydiradi.",
    danger: "o'rta",
  },
  "agno3-naoh": {
    table: null,
    title: "AgNO₃ + ishqor → Ag₂O",
    equation: ["2AgNO₃ + 2NaOH → Ag₂O↓ + 2NaNO₃ + H₂O"],
    type: "Ion almashinish (cho'kma); AgOH barqaror emas",
    observation: "Oq emas, balki qo'ng'ir cho'kma tushadi — kumush gidroksid darhol oksidga aylanadi.",
    safety: "AgNO₃ terida qora dog' qoldiradi; kumush chiqindisi alohida idishga.",
    danger: "past",
  },
  "agcl-nh3": {
    table: null,
    title: "AgCl ortiqcha ammiakda eriydi",
    equation: ["AgCl + 2NH₃ → [Ag(NH₃)₂]⁺ + Cl⁻"],
    type: "Kompleks birikma hosil bo'lishi (qaytar)",
    observation: "Oq cho'kma ammiakda erib ketadi va eritma tiniqlashadi; kislota qo'shilsa kompleks buzilib, cho'kma yana tushadi. AgI erimaydi.",
    safety: "Ammiakli kumush eritmasini saqlab qo'yish xavfli — portlovchi birikma hosil bo'ladi; ishlatilgach darhol chiqindiga.",
    danger: "o'rta",
  },
  "metal-nahco3": {
    table: null,
    title: "Soda eritmasi + mis yoki temir tuzi",
    equation: ["2CuSO₄ + 4NaHCO₃ → (CuOH)₂CO₃↓ + 2Na₂SO₄ + 3CO₂↑ + H₂O", "FeCl₃ + 3NaHCO₃ → Fe(OH)₃↓ + 3NaCl + 3CO₂↑"],
    type: "Ion almashinish (cho'kma va gaz)",
    observation: "Mis tuzi bilan ko'kish-yashil, temir tuzi bilan qo'ng'ir cho'kma tushadi va shu bilan birga CO₂ pufakchalari chiqadi.",
    safety: "Past xavf; mis chiqindisi alohida idishga.",
    danger: "past",
  },
  "kmno4-ki": {
    table: null,
    title: "KMnO₄ + KI",
    equation: ["2KMnO₄ + 10KI + 8H₂SO₄ → 2MnSO₄ + 5I₂ + 6K₂SO₄ + 8H₂O", "kislotasiz: MnO₂↓ va I₂ hosil bo'ladi"],
    type: "Oksidlanish-qaytarilish",
    observation: "Binafsha rang yo'qoladi va eritma qo'ng'ir tus oladi (yod); kislotasiz muhitda qo'ng'ir MnO₂ cho'kmasi ham tushadi.",
    safety: "KMnO₄ kuchli oksidlovchi; yod dog' qoldiradi.",
    danger: "o'rta",
  },
  "fecl3-h2o2": {
    table: null,
    title: "FeCl₃ — H₂O₂ uchun katalizator",
    equation: ["2H₂O₂ →(Fe³⁺) 2H₂O + O₂↑"],
    type: "Katalitik parchalanish",
    observation: "Sariq-qo'ng'ir eritmada kislorod pufakchalari chiqa boshlaydi; temir(III) ioni sarflanmaydi.",
    safety: "H₂O₂ teriga tegsa oqartiradi; idish og'zini yopmang.",
    danger: "o'rta",
  },
  "cl2-naoh": {
    table: null,
    title: "Xlorning ishqorda yutilishi",
    equation: ["Cl₂ + 2NaOH → NaCl + NaClO + H₂O"],
    type: "Disproporsiyalanish (oksidlanish-qaytarilish)",
    observation: "Sarg'ish-yashil gaz ishqor eritmasiga yutiladi va rangsiz eritma hosil bo'ladi — ortiqcha xlor shu yo'l bilan zararsizlantiriladi.",
    safety: "Xlor zaharli: ishni mo'rili shkafda bajaring.",
    danger: "yuqori",
  },
  "nahco3-heat": {
    table: null,
    title: "Ichimlik sodasining qizdirilganda parchalanishi",
    equation: ["2NaHCO₃ →(t) Na₂CO₃ + CO₂↑ + H₂O"],
    type: "Parchalanish (qizdirilganda)",
    observation: "Qizdirilganda kukundan CO₂ ajraladi va namlik ko'rinadi; qoldiq — natriy karbonat.",
    safety: "Issiq probirka; og'zini odamlarga qaratmang.",
    danger: "past",
  },
};
