export { default as HeroSection } from "./HeroSection";
export { default as StatsSection } from "./StatsSection";
export { default as SubjectsSection } from "./SubjectsSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as ProcessSection } from "./ProcessSection";
export { default as CtaSection } from "./CtaSection";
export { default as LandingFooter } from "./LandingFooter";
export { default as Reveal } from "./Reveal";
export { default as SectionHead } from "./SectionHead";
